import { SendHorizontal } from 'lucide-react'
import { FormEvent, KeyboardEvent, useState } from 'react'

export function ChatInput({ onSend, disabled }: { onSend: (message:string)=>void; disabled:boolean }) {
  const [value,setValue]=useState('')
  const [error,setError]=useState('')
  const sensitive=(message:string)=>/\b[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}\b|0\d{1,2}-\d{3,4}-\d{4}|(?<!\d)(?:20)?\d{8,10}(?!\d)/.test(message)
  const submit=(event?:FormEvent)=>{event?.preventDefault(); const message=value.trim(); if(!message||disabled)return;if(sensitive(message)){setError('학번, 전화번호, 이메일 등 개인정보를 제거한 뒤 다시 질문해 주세요.');return}setError('');onSend(message);setValue('')}
  const keyDown=(event:KeyboardEvent<HTMLTextAreaElement>)=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();submit()}}
  return <form onSubmit={submit} className="border-t border-slate-200 bg-white px-4 py-3 md:px-6"><div className="mx-auto max-w-5xl"><label htmlFor="chat-input" className="mb-1.5 block text-xs font-bold text-slate-600">질문 입력</label><div className={`flex items-end gap-2 rounded-2xl border bg-white p-2 shadow-sm transition focus-within:ring-4 ${error?'border-red-400 focus-within:ring-red-100':'border-slate-300 focus-within:border-brand-500 focus-within:ring-brand-100'}`}><textarea id="chat-input" value={value} onChange={e=>{setValue(e.target.value.slice(0,1000));if(error)setError('')}} onKeyDown={keyDown} rows={1} disabled={disabled} aria-describedby={error?'chat-error':'chat-helper'} aria-invalid={Boolean(error)} placeholder="예: 2학기 수강신청은 언제야?" className="max-h-32 min-h-11 flex-1 resize-none border-0 bg-transparent px-2 py-2.5 text-base leading-6 text-slate-800 outline-none placeholder:text-slate-400 disabled:opacity-60"/><button type="submit" disabled={disabled||!value.trim()} aria-label={disabled?'답변을 기다리는 중':'질문 전송'} className="grid h-11 w-11 shrink-0 cursor-pointer place-items-center rounded-xl bg-brand-600 text-white transition hover:bg-brand-700 disabled:cursor-not-allowed disabled:bg-slate-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-600"><SendHorizontal size={19}/></button></div>{error?<p id="chat-error" role="alert" className="mt-2 text-sm font-semibold text-red-700">{error}</p>:<p id="chat-helper" className="mt-2 text-center text-[11px] text-slate-500">개인정보는 입력하지 마세요. Enter 전송 · Shift+Enter 줄바꿈</p>}</div></form>
}
